class SearchController < ApplicationController
  resource_description do
    short 'Search services'
    full_description <<-END
The services contained in the Open Service Broker are described using the [SDL-NG framework](https://github.com/TU-Berlin-SNET/sdl-ng), please refer it to get information about the general syntax of the service descriptions. (currently not up-to-date!)

    END
  end

  respond_to :html, :xml, :json

  api :GET, 'search', 'Returns a list of services.'
  description <<-END

  END
  formats ['html']
  def search
    # delete unused query parameter utf8 generated by ruby
    request.query_parameters.delete("utf8")

    #TODO: check if given parameters exist / security
    #choices = compendium.type_instances.select { |key, value| key.to_s.match(/^choice\d+/) }

    # get all services with the requested parameters
    @services = Service.filter(request.query_parameters).to_a

    @params = request.query_parameters
  end
end